### ISSUE TITLE
Build packages for for linux-x64-musl target

### ISSUE THREAD

**Issue by penberg** [libsql/libsql-js#32]

**Comment by penberg** [comment]
We build packages now, but they don't work:

```
```
[0] 1 | (function (id){"use strict";var cached=@requireMap.@get(id);const last5=id.substring(id.length-5);if(cached)return cached.exports;if(last5===".json"){var fs=globalThis[Symbol.for("_fs")]||=@Bun.fs(),exports=JSON.parse(fs.readFileSync(id,"utf8"));return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}else if(last5===".node"){const module=@createCommonJSModule(id,{},!0);return process.dlopen(module,id),@requireMap.@set(id,module),module.exports}else if(last5===".toml"){var fs=globalThis[Symbol.for("_fs")]||=@Bun.fs(),exports=@Bun.TOML.parse(fs.readFileSync(id,"utf8"));return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}else{var exports=@requireESM(id);const cachedModule=@requireMap.@get(id);if(cachedModule)return cachedModule.exports;return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}})
[0]                        ^
[0] TypeError: libc.so: cannot open shared object file: No such file or directory
[0]       at internalRequire (:1:20)
[0]       at /mnt/d/htmlcss/the-beth-stack/node_modules/libsql/index.js:26:23
[0]       at globalThis (/mnt/d/htmlcss/the-beth-stack/node_modules/libsql/index.js:313:29)
[0] 1 | (function (id){"use strict";var cached=@requireMap.@get(id);const last5=id.substring(id.length-5);if(cached)return cached.exports;if(last5===".json"){var fs=globalThis[Symbol.for("_fs")]||=@Bun.fs(),exports=JSON.parse(fs.readFileSync(id,"utf8"));return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}else if(last5===".node"){const module=@createCommonJSModule(id,{},!0);return process.dlopen(module,id),@requireMap.@set(id,module),module.exports}else if(last5===".toml"){var fs=globalThis[Symbol.for("_fs")]||=@Bun.fs(),exports=@Bun.TOML.parse(fs.readFileSync(id,"utf8"));return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}else{var exports=@requireESM(id);const cachedModule=@requireMap.@get(id);if(cachedModule)return cachedModule.exports;return @requireMap.@set(id,@createCommonJSModule(id,exports,!0)),exports}})
[0]                        ^
[0] TypeError: libc.so: cannot open shared object file: No such file or directory
[0]       at internalRequire (:1:20)
[0]       at /mnt/d/htmlcss/the-beth-stack/node_modules/libsql/index.js:26:23
[0]       at globalThis (/mnt/d/htmlcss/the-beth-stack/node_modules/libsql/index.js:313:29)
[1] 
```

**Comment by penberg** [comment]
Fixed in 0c52b3be90969721a9ddfa5ac3d889db4e384e01, although the real problem was actually Bun trying to load the wrong thing, fixed in 39c8ac802093282718459140ab3562baf91f183c
